# Generated by Django 3.1.1 on 2020-09-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='duration of event'),
            preserve_default=False,
        ),
    ]
